
# Tells Concourse which type of worker this task should run on
platform: linux
# The command Concourse will run inside the container
# echo "Hello Concourse"
inputs: # pass concourse-examples into this task step
- name: resource-tutorial
run:
  path: python
  args:
  - resource-tutorial/welcome_person.py
