
# Tells Concourse which type of worker this task should run on
platform: linux
# The command Concourse will run inside the container
# echo "Hello Concourse"
inputs: # pass concourse-examples into this task step
- name: resource-tutorial
run:
  path: python
  dir: resource-tutorial
  args:
  - -exc
  - |
      python welcome_person.py

      git config --global user.name "$GIT_USER"
      git config --global user.email "$GIT_EMAIL"

      git add personas.json
      git commit -m "Update shown persons via Concourse pipeline"
      git push origin "$GIT_BRANCH"
