resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/gonev/concourse.git
    branch: main
- name: every-5m
  type: time
  source:
    interval: 5m
jobs:
- name: hello-sap-job
  plan:
  - get: every-5m
    trigger: true
  - get: resource-tutorial
  - task: hello-sap-task
    file: resource-tutorial/tasks/task_hello_sap_python.yml
  - task: hello-sap-docker
    file: resource-tutorial/tasks/task_hello_sap_docker.yml
